### ISSUE TITLE
Market landscape

### ISSUE THREAD

**Issue by sarah-arrrgh** [root-systems/cobuy-meta#6]
### local
- [bucky box](http://www.buckybox.com) - focus on supplier (vs our focus is on consumer). consumer buys a pre-filled box +/- a few things. 
- [oooby](https://www.ooooby.org) - focus on locally grown food and artisan products. goes from suppliers to consumers.
### international
- [open food network](https://openfoodnetwork.org) - too rigid/opinionated. doesn’t fit with our use case
- [buying club software](http://www.buyingclubsoftware.com/tour) - looks pretty close to our use case, needs more investigation?
- [foodsoft](https://github.com/foodcoops/foodsoft) - possibly open source food coop software?
- [manage my coop](http://www.managemy.coop/) - run by peeps in oregon, looks active on [facebook](https://www.facebook.com/managemycoop)
- [food club](http://foodclub.org/)

---

this looks interesting - flagging for future investigation [food coop initiative](http://www.foodcoopinitiative.coop/)

**Comment by ahdinosaur** [comment]
[how the co-op i used to live in does their food system](https://www.bsc.coop/index.php/food/how-the-co-op-food-system-works)
