### ISSUE TITLE
Users and customers

### ISSUE THREAD

**Issue by sarah-arrrgh** [root-systems/cobuy-meta#7]
original question:

> an idea of how many "customers" and "users" we would have. roughly. customers being people who directly or indirectly pay to use our service. users being people who use our service but don’t pay for it.

(from Mikey) maybe related questions:
- how many consumer coops exist currently?
- how many consumer coops start per year?
- how many consumer coops die per year?
- somehow to measure potential coops that never start...
- how much are consumer coops buying (collective purchasing power) per year?
- how much does it cost (time, money, stress, etc) to administrate a consumer coop?

**Comment by ahdinosaur** [comment]
[world co-op monitor](http://monitor.coop/)

> ## WHOLESALE AND RETAIL TRADE:
> 
> This sector includes co-operatives formed to purchase and supply goods and services at competitive conditions in the interest of their members.Overall, data pertaining to this sector was collected for 450 co-operatives distributed in 42 countries with a total turnover in 2013 of 605.48 billion  US dollars. Looking at the co-operatives  with a turnover of over 100 million US dollars in this sector, there are 400 co-operatives distributed in 35 countries, with a total turnover of 603.91 billion US dollars
> 
> ![THE 20 LARGEST CO-OPERATIVES IN THE WHOLESALE AND RETAIL TRADE SECTOR BY TURNOVER](https://cloud.githubusercontent.com/assets/719605/15597643/2b1788b2-2426-11e6-9651-88c894c94f5e.png)
> 
> ![THE 20 LARGEST CO-OPERATIVES IN THE WHOLESALE AND RETAIL TRADE SECTOR BY TURNOVER ON GDP PER CAPITA](https://cloud.githubusercontent.com/assets/719605/15597642/2af25ef2-2426-11e6-8231-cf89ce7402d1.png)

**Comment by ahdinosaur** [comment]
- [consumer co-ops worldwide](http://www.ccw.coop/en/)
  - [members](http://www.ccw.coop/en/members/members-list)
  - [reports](http://www.ccw.coop/en/publications/reports-memos)
  - [latest 2013 report](http://www.ccw.coop/images/stories/reports/4th_Edition_Euro_Coop_Climate_Change_Report.pdf), talks a lot about consumer co-ops as a means to reduce waste. :sparkles: 
- [survey of co-op capital](https://filene.org/research/report/survey-of-co-operative-capital1)
